name = "audit"
description = "指定されたプロジェクトの監査情報を収集します。"
prompt = """
まず、scripts/collect-audit-context.ts スクリプトを実行してください。
スクリプトの出力結果を**分析の出発点**としてください。ただし、正確な判断を下すためには、**プロジェクト内の関連ファイルを直接読み込み、内容を深く理解する**必要があります。全ての情報を踏まえた上で、指定されたプロジェクトの現状、課題、そして次に取るべきアクションを特定してください。

以下の監査情報を確認してください:
{{stdout}}
"""
command = "pnpm tsx scripts/collect-audit-context.ts {{.project-name}}"

[[argument]]
name = "project-name"
description = "監査対象のプロジェクト名 (例: spotify-automation)"
required = true
