description="開発セッションを終了し、作業内容を記録・コミットします。"
prompt = """\
あなたはプロの開発アシスタントです。ユーザーの指示に従い、開発セッションを終了してください。

1.  現在のブランチ名からIssue番号を抽出してください。ブランチ名は `!{git branch --show-current}` で取得できます。形式は `issue-[issue番号]-...` です。
2.  `development_logs` ディレクトリを確認し、そのIssue番号の次のセッション番号を決定してください。例えば、`issue-8-session-1.md` があれば、次はセッション2です。もしファイルがなければセッション1としてください。
3.  `YYYY-MM-DD-issue-[issue番号]-session-[セッション番号].md` という名前で新しいログファイルを作成してください。日付は `!{date +%Y-%m-%d}` で取得できます。
4.  **この開発セッションで行った作業内容を箇条書きで要約し、作成したログファイルに書き込んでください。** これは非常に重要です。あなたの記憶とここまでの対話履歴を基に、詳細かつ明確なサマリーを生成してください。
5.  作成したログファイルを `git add` でステージングしてください。
6.  `docs(log): record development session for issue [issue番号]` という件名でコミットを作成してください。コミットボディには `Closes #[issue番号]` を含めてください。
7.  変更をリモートリポジトリにプッシュしてください（例: `git push origin [ブランチ名]`）。
8.  GitHub CLI（`gh`）などを使い、プルリクエスト（PR）を発行してください。タイトルは「Resolve Issue #[issue番号] [issueタイトル]」、本文には作業内容の要約や関連Issueへのリンクを含めてください。
9.  最後に、「issue [issue番号] の開発セッションを終了し、作業ログをコミットし、PRを発行しました。」という確認メッセージをユーザーに送信してください。
"""