description="開発セッションを終了し、PRを作成してCIの結果を監視します。"
prompt = """
あなたはプロの開発アシスタントです。AGENTS.MDの指示に基づき、以下の手順で開発セッションを終了してください。

**ステップ 1: E2Eテストの実施**

1.  変更の影響を受けるプロジェクトのテストを実行し、すべてのテストが成功することを確認してください (`pnpm nx affected:test`)。
2.  テストが失敗した場合は、問題を修正し、再度テストを実行してください。すべてのテストが成功するまでこのステップを繰り返してください。

**ステップ 2: 作業内容の記録とコミット**

1.  現在のブランチ名を取得してください (`git branch --show-current`)。
2.  ブランチ名からIssue番号を抽出してください。
3.  `development_logs` ディレクトリに次のセッション番号でログファイルを作成してください (`YYYY-MM-DD-issue-[issue番号]-session-[セッション番号].md`)。
4.  **この開発セッションで行った作業内容を箇条書きで要約し、作成したログファイルに書き込んでください。**
5.  ログファイルをステージングしてください (`git add <logfile>`)。
6.  `docs(log): record development session for issue [issue番号]` というメッセージでコミットしてください (`git commit -m "..."`)。

**ステップ 3: プルリクエストの作成とCIの監視**

1.  変更をリモートリポジトリにプッシュしてください (`git push origin <branch_name> --force`)。
2.  Issueのタイトルを取得してください (`gh issue view <issue_number> --json title -q .title`)。
3.  プルリクエストを作成してください (`gh pr create --title "..." --body "..."`)。もしPRが既に存在する場合は、そのURLを取得してください (`gh pr view --json url -q .url`)。
4.  CIの完了を監視してください (`gh pr checks <pr_url> --watch --interval 5`)。
5.  CIが成功した場合は、PRにレビューコメントが付いているかを確認してください。もしレビューコメントが存在する場合は、その内容を検証し、問題なければ採用してください。
6.  手順4と5を繰り返し、最終的にCIが成功しレビューコメントへの対応が完了した場合は、`main`ブランチに切り替えてください (`git checkout main`)。
"""