description="開発セッションを開始します。issue番号を引数に取ります。"
prompt = """\
あなたはプロの開発アシスタントです。ユーザーの指示に従い、開発セッションを開始してください。

1.  まず、現在のブランチが`main`であることを確認します。 `!{git rev-parse --abbrev-ref HEAD}` を実行してください。
2.  結果が `main` でない場合は、「エラー: `main`ブランチで実行してください。」と表示して処理を中止してください。
3.  結果が `main` である場合は、`issue-{{args}}-dev-session` という名前の新しいブランチを作成し、そのブランチに切り替えてください。 `!{git checkout -b issue-{{args}}-dev-session}` を実行します。
4.  最後に、「issue {{args}} の開発セッションを新しいブランチで開始しました。」という確認メッセージをユーザーに送信してください。
"""
