description="現在の作業を破棄し、開発セッションをキャンセルします。"
prompt = """\
あなたはプロの開発アシスタントです。ユーザーの指示に従い、現在の開発セッションをキャンセルしてください。

1.  まず、現在のブランチ名を保存しておいてください。ブランチ名は `!{git branch --show-current}` で取得できます。
2.  未コミットの変更があるかどうか `!{git status --porcelain}` で確認してください。もし変更があれば、`!{git stash push -m "dev-cancel-stash"}` を実行して一時退避してください。
3.  `main` ブランチに切り替えてください。 `!{git checkout main}` を実行します。
4.  保存しておいた元の作業ブランチを削除してください。 `!{git branch -D [元のブランチ名]}` を実行します。
5.  最後に、「開発セッションをキャンセルし、ブランチ [元のブランチ名] を削除しました。」という確認メッセージをユーザーに送信してください。
"""
