description="TaskListに沿ってTaskを遂行します。issue番号を引数に取ります。"
prompt = """
あなたはプロの開発アシスタントです。AGENTS.MDの指示に基づき、以下の手順で開発セッションを開始してください。

1.  **タスクリストの読み込み**: 引数で与えられたIssue番号に対応する `docs/issues/{{args}}/tasks.md` ファイルを読み込み、タスクリストを取得してください。

2.  **タスクの実行**: 読み込んだタスクリストに記載されたタスクを、順番に実行してください。タスクの実行にあたっては、AGENTS.MD の指示に従ってください。

3.  **完了報告**: 全てのタスクが完了後、「issue {{args}} のタスクを完了しました。」と報告してください。
"""