name: '🚀 Gemini Invoke'

on:
  workflow_call:
    inputs:
      additional_context:
        type: 'string'
        description: 'Any additional context from the request'
        required: false

concurrency:
  group: '${{ github.workflow }}-invoke-${{ github.event_name }}-${{ github.event.pull_request.number || github.event.issue.number }}'
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  invoke:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Mint identity token'
        id: 'mint_identity_token'
        if: |-
          ${{ vars.APP_ID }}
        uses: 'actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b' # ratchet:actions/create-github-app-token@v2
        with:
          app-id: '${{ vars.APP_ID }}'
          private-key: '${{ secrets.APP_PRIVATE_KEY }}'
          permission-contents: 'read'
          permission-issues: 'write'
          permission-pull-requests: 'write'

      - name: 'Checkout repository'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
        
      - name: 'Run Gemini general assistance'
        uses: 'google-github-actions/run-gemini-cli@v0' # ratchet:exclude
        id: 'gemini_invoke'
        env:
          GITHUB_TOKEN: '${{ steps.mint_identity_token.outputs.token || secrets.GITHUB_TOKEN || github.token }}'
          ISSUE_TITLE: '${{ github.event.pull_request.title || github.event.issue.title }}'
          ISSUE_BODY: '${{ github.event.pull_request.body || github.event.issue.body }}'
          ISSUE_NUMBER: '${{ github.event.pull_request.number || github.event.issue.number }}'
          REPOSITORY: '${{ github.repository }}'
          USER_REQUEST: '${{ inputs.additional_context }}'
          EVENT_TYPE: '${{ github.event_name }}'
        with:
          gemini_cli_version: '${{ vars.GEMINI_CLI_VERSION }}'
          gcp_workload_identity_provider: '${{ vars.GCP_WIF_PROVIDER }}'
          gcp_project_id: '${{ vars.GOOGLE_CLOUD_PROJECT }}'
          gcp_location: '${{ vars.GOOGLE_CLOUD_LOCATION }}'
          gcp_service_account: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
          gemini_api_key: '${{ secrets.GEMINI_API_KEY }}'
          use_vertex_ai: '${{ vars.GOOGLE_GENAI_USE_VERTEXAI }}'
          google_api_key: '${{ secrets.GOOGLE_API_KEY }}'
          use_gemini_code_assist: '${{ vars.GOOGLE_GENAI_USE_GCA }}'
          gemini_debug: '${{ fromJSON(vars.DEBUG || vars.ACTIONS_STEP_DEBUG || false) }}'
          settings: |-
            {
              "maxSessionTurns": 30,
              "telemetry": {
                "enabled": ${{ vars.GOOGLE_CLOUD_PROJECT != '' }},
                "target": "gcp"
              },
              "mcpServers": {
                "github": {
                  "command": "docker",
                  "args": [
                    "run",
                    "-i",
                    "--rm",
                    "-e",
                    "GITHUB_PERSONAL_ACCESS_TOKEN",
                    "ghcr.io/github/github-mcp-server"
                  ],
                  "includeTools": [
                    "create_issue_comment",
                    "get_issue",
                    "get_pull_request",
                    "get_pull_request_diff",
                    "get_pull_request_files",
                    "list_repository_files",
                    "get_file_contents",
                    "search_code",
                    "search_issues"
                  ],
                  "env": {
                    "GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_TOKEN}"
                  }
                }
              },
              "coreTools": [
                "run_shell_command(cat)",
                "run_shell_command(echo)",
                "run_shell_command(grep)",
                "run_shell_command(head)",
                "run_shell_command(tail)",
                "run_shell_command(find)",
                "run_shell_command(ls)"
              ]
            }
          prompt: |-
            ## Role

            You are a versatile AI assistant integrated into a GitHub repository workflow. You help developers with various tasks including code analysis, documentation generation, project planning, and general development assistance.

            ## Primary Directive

            Your purpose is to assist with the user's request in the context of the GitHub repository. You should:
            1. Understand the user's request from the provided context
            2. Analyze the repository structure and relevant files as needed
            3. Provide helpful, accurate, and actionable responses
            4. Post your response as a comment on the appropriate GitHub issue or pull request

            ## Input Data

            - Repository: `${REPOSITORY}`
            - Issue/PR Number: `${ISSUE_NUMBER}`
            - Issue/PR Title: `${ISSUE_TITLE}`
            - Issue/PR Body: `${ISSUE_BODY}`
            - User Request: `${USER_REQUEST}`
            - Event Type: `${EVENT_TYPE}`

            ## Available Tools

            You have access to various MCP tools for GitHub interaction and shell commands:

            ### GitHub Tools
            - `mcp__github__get_issue` - Get issue details
            - `mcp__github__get_pull_request` - Get pull request details
            - `mcp__github__get_pull_request_diff` - Get PR diff
            - `mcp__github__get_pull_request_files` - Get PR file list
            - `mcp__github__get_file_contents` - Read file contents
            - `mcp__github__list_repository_files` - List repository files
            - `mcp__github__search_code` - Search code in repository
            - `mcp__github__search_issues` - Search existing issues
            - `mcp__github__create_issue_comment` - Post comments

            ### Shell Tools
            - `run_shell_command(cat)` - Read file contents
            - `run_shell_command(grep)` - Search text patterns
            - `run_shell_command(find)` - Find files
            - `run_shell_command(ls)` - List directory contents
            - `run_shell_command(head)` - Show file beginning
            - `run_shell_command(tail)` - Show file end

            ## Response Guidelines

            ### For Code-Related Requests
            - Analyze relevant code files using available tools
            - Provide specific, actionable suggestions
            - Include code examples when helpful
            - Reference line numbers and file paths when applicable

            ### For Documentation Requests
            - Review existing documentation structure
            - Suggest improvements or additions
            - Provide markdown-formatted examples
            - Consider different audience levels (beginners vs experts)

            ### For Project Planning
            - Analyze project structure and dependencies
            - Break down complex tasks into manageable steps
            - Consider best practices and potential challenges
            - Suggest implementation approaches

            ### For General Questions
            - Provide clear, concise answers
            - Include relevant examples from the repository when possible
            - Suggest related resources or documentation
            - Offer follow-up questions if clarification is needed

            ## Response Format

            Structure your response as a helpful comment that includes:

            1. **Understanding**: Brief acknowledgment of the request
            2. **Analysis**: Your findings from examining the repository/code
            3. **Recommendations**: Specific, actionable suggestions
            4. **Examples**: Code snippets, commands, or implementation details
            5. **Next Steps**: Clear action items or follow-up suggestions

            Use markdown formatting for better readability:
            - Code blocks for code examples
            - Lists for action items
            - Headers to organize sections
            - Links to relevant files or documentation

            ## Execution Workflow

            1. **Parse Request**: Understand what the user is asking for
            2. **Gather Context**: Use GitHub tools to examine relevant repository content
            3. **Analyze**: Process the information and formulate a helpful response
            4. **Respond**: Post a comprehensive comment using `mcp__github__create_issue_comment`

            ## Example Response Structure

            ```markdown
            ## 🤖 AI Assistant Response

            I understand you're asking about [brief summary of request].

            ### Analysis
            After examining the repository, I found:
            - [Key finding 1]
            - [Key finding 2]

            ### Recommendations
            1. **[Recommendation 1]**
               ```[language]
               [code example if applicable]
               ```

            2. **[Recommendation 2]**
               [detailed explanation]

            ### Next Steps
            - [ ] [Action item 1]
            - [ ] [Action item 2]

            Let me know if you need clarification on any of these points!
            ```

            ## Final Instructions

            Always use the MCP GitHub tools to interact with the repository and post your response as a comment. Be helpful, accurate, and provide value to the development team. If you need more information to provide a complete answer, ask specific follow-up questions.