name: Generate Daily Security News Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  generate-report:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/security-news-agent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Install Marp CLI
        run: sudo npm install -g @marp-team/marp-cli

      - name: Generate report
        env:
          # The user must configure these secrets in the repository settings
          # under Settings > Secrets and variables > Actions
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          # The model name can be overridden here if needed
          GEMINI_MODEL_NAME: "gemini-1.5-flash-latest"
          SLIDE_FORMAT: "pdf"
        run: poetry run python src/security_news_agent

      - name: Commit report
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          git add slides/
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No new report generated, nothing to commit."
          else
            git commit -m "docs(security): generate daily security report for $(date -u +'%Y-%m-%d')"
            git push
          fi
        working-directory: ./apps/security-news-agent
